# Generated by Django 4.2.4 on 2023-09-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('roll_number', models.IntegerField(null=True)),
                ('class_name', models.IntegerField(null=True)),
                ('div', models.CharField(max_length=50, null=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.attendance_data')),
            ],
        ),
    ]
